[JU-4 figma design has been completed.]
archis-academy/june-frontend-e-tutor-lms-1 pull request #3
Opened 2024-07-12 19:51 UTC by Sametcangozuacik

2024-07-16 14:36 UTC, aydinnMustafa requested changes

2024-07-16 14:36 UTC, aydinnMustafa commented on src/app/layout.tsx
> +        <FeaturedCourses />
Component Home içerisinde render edilecek

2024-07-16 14:36 UTC, aydinnMustafa commented on src/app/components/FeaturedCourses/featured-courses.css
> +
Css yerine sass kullanılacak

2024-07-16 14:36 UTC, aydinnMustafa commented on src/app/components/FeaturedCourses/featured-courses.tsx
> +            <div className='featured-section-box'>
FeatureCourseCard adında bir component oluşturulup card için gerekli veriler props olarak dinamik alınacak. Bu component verilen data kadar card gösterecek şekilde dinamik çalışmalı.
- Component klasörü src içerisinde olacak app içerisinden çıkartılacak.

2024-07-25 14:26 UTC, aydinnMustafa requested changes

2024-07-25 14:26 UTC, aydinnMustafa commented on src/app/components/FeaturedCourses/featuredcourses.tsx
> +    const [courses, setCourses] = useState<Course[]>(featureCourse);
Burada data değişmeyeceği için state'e ihtiyacımız yok. Yukarıda tanımlanan data direkt map edilebilir

2024-07-25 14:26 UTC, aydinnMustafa commented on src/app/components/FeaturedCourses/featuredcourses.tsx
> +        image: "@/public/corleone.svg"
Public içerisine FeaturedCourses klasörünün oluşturulduğunu varsayarsak görsel "FeaturedCourses/course-one.svg" ile import edilebilir

2024-07-30 13:51 UTC, merged

2024-07-30 13:54 UTC, Sametcangozuacik commented
s